name: Publish to npm beta

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: publish to npm@beta
        run: |
          npm install -g yarn
          yarn install
          yarn run test
          yarn publish --non-interactive --tag beta
        env:
          CI: true
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
