name: Run test on pull

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - ipfs-query

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Create mongo Docker container
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v1.0.1
        with:
          image-version: latest
          port: 27017
      - name: build and test
        run: |
          npm install -g yarn
          yarn install
          yarn run test
        env:
          CI: true
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
